#!/bin/bash

echo Starting statorange with parameters: $@

tmp_path=`mktemp -d`
echo Working directory: $tmp_path

xset fp- /usr/local/lib/statorange/misc
xset fp+ /usr/local/lib/statorange/misc

# Define fonts.
normal_font="-f -misc-fixed-medium-r-normal--12-120-75-75-C-70-iso10646-1"
normal_font="-f drift"
# powerline_icons="-f -xos4-terminusicons2-medium-r-normal--12-120-72-72-c-60-iso8859-1"
powerline_icons="-f -xos4-terminusicons2mono-medium-r-normal--12-120-72-72-m-60-iso8859-1"

# Define commands and file paths.
lemonbar_cmd="lemonbar $normal_font $powerline_icons -a 30 -u -1"
# lemonbar_cmd="lemonbar $normal_font -u -1 -a 30"
statorange_fifo=$tmp_path"/statorange.fifo"
shell_cmd="/bin/bash"

rm -f $statorange_fifo
mkfifo $statorange_fifo

while :
do
    echo Launching statorange...
    echo "statorange "$@" 1> $statorange_fifo &"
    statorange "$@" 1> $statorange_fifo &
    statorange_pid=$!
    echo PID: $statorange_pid

    echo Launching lemonbar...
    echo "cat $statorange_fifo | $lemonbar_cmd | $shell_cmd -v &"
    cat $statorange_fifo | $lemonbar_cmd | $shell_cmd -v &
    lemonbar_pid=$!
    echo PID: $lemonbar_pid

    wait $statorange_pid
    exit_value=$?
    echo $statorange_cmd terminated with exit value $exit_value

    sleep 5
done
